//
// QUIVER Sprites
//

//
// Electrical spark #1 (environmental)
//
$spritename     spark1
$type           vp_parallel
$load           \quiver\valve\sprites\bmp\spark1.bmp
$frame          0       0       40      40
$frame          40      0       40      40
$frame          80      0       40      40
$frame          0       80       8       8


//
// new glass shards for broken windows
//
$spritename     shard
$type           vp_parallel
$load           \quiver\valve\sprites\bmp\shard.bmp
$frame          0       0       24      24
$frame          24      0       24      16
$frame          48      0       16      16
$frame          64      0       8       16
$frame          72      0       16      16
$frame          88      0       24      8

//
// Bubble sprite
//
$spritename     bubble
$type           vp_parallel
$load           \quiver\valve\sprites\bmp\bubble.bmp
$frame          0       0       16      16
