; these graphics are grabbed in a single wadfile that will be loaded at
; quake startup time.

$dest   valve/gfx.wad

;=============================================================================

$loadbmp        valve/gfx/hud/640_bl.bmp
640_BL      QPIC        -1      -1      -1      -1

$loadbmp        valve/gfx/hud/640_UL.bmp
640_UL      QPIC        -1      -1      -1      -1

$loadbmp        valve/gfx/hud/640_br.bmp
640_BR      QPIC        -1      -1      -1      -1

$loadbmp        valve/gfx/hud/640_mr.bmp
640_MR      QPIC        -1      -1      -1      -1


$loadbmp        valve/gfx/hud/640_bl_t.bmp
640_BL_T      QPIC        -1      -1      -1      -1

$loadbmp        valve/gfx/hud/640_UL_t.bmp
640_UL_T      QPIC        -1      -1      -1      -1

$loadbmp        valve/gfx/hud/640_br_t.bmp
640_BR_T      QPIC        -1      -1      -1      -1

$loadbmp        valve/gfx/hud/640_mr_t.bmp
640_MR_T      QPIC        -1      -1      -1      -1

$loadbmp        valve/gfx/lambda.bmp
lambda      QPIC        -1      -1      -1      -1

$loadbmp        valve/gfx/lambda64.bmp
lambda64      QPIC        -1      -1      -1      -1

$loadbmp        valve/gfx/lambda32.bmp
lambda32      QPIC        -1      -1      -1      -1

$loadbmp        valve/gfx/xlambda.bmp
xlambda      QPIC       -1      -1      -1      -1


$loadbmp        valve/gfx/xlambda1.bmp
xlambda1      QPIC        -1     -1      -1      -1


; System font
$loadbmp valve/gfx/status/qfont01.bmp
conchars        font    13      32  0 0 159 93   160 0 94 159 193   -1

$loadbmp valve/gfx/black.bmp
backtile        qpic            0               128             64              64


$loadbmp        valve/gfx/w0.bmp
weapon0      QPIC        -1      -1      -1      -1

$loadbmp        valve/gfx/w1.bmp
weapon1      QPIC        -1      -1      -1      -1

$loadbmp        valve/gfx/w2.bmp
weapon2      QPIC        -1      -1      -1      -1

$loadbmp        valve/gfx/w3.bmp
weapon3      QPIC        -1      -1      -1      -1

$loadbmp        valve/gfx/w4.bmp
weapon4      QPIC        -1      -1      -1      -1

$loadbmp        valve/gfx/w5.bmp
weapon5      QPIC        -1      -1      -1      -1

$loadbmp        valve/gfx/w6.bmp
weapon6      QPIC        -1      -1      -1      -1

$loadbmp        valve/gfx/w7.bmp
weapon7      QPIC        -1      -1      -1      -1

$loadbmp        valve/gfx/w8.bmp
weapon8      QPIC        -1      -1      -1      -1

$loadbmp        valve/gfx/w9.bmp
weapon9      QPIC        -1      -1      -1      -1

$loadbmp        valve/gfx/hud/pain_left.bmp
pain_left      QPIC        -1      -1      -1      -1

$loadbmp        valve/gfx/hud/pain_right.bmp
pain_right      QPIC        -1      -1      -1      -1

$loadbmp        valve/gfx/hud/pain_top.bmp
pain_top      QPIC        -1      -1      -1      -1

$loadbmp        valve/gfx/hud/pain_bot.bmp
pain_bot      QPIC        -1      -1      -1      -1
