name: Build

on:
  push:
    branches: [ "main" ]
    paths: [ "*.cs", "*.sh" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4

    - name: Build & Install Mono
      run: ./ci/install-mono.sh

    - name: Compile
      run: ./compile.sh

    - name: Package
      run: zip -r CLI_build.zip bin/*

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: HLTextureToolsCLI
        path: |
          ./bin/*

    - name: Remove previous release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release delete "continuous" \
              --yes \
              --cleanup-tag \
              --repo "Buggem/HL-Texture-Tools-CLI" || true
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        name: Latest Build (GHA)
        tag: continuous
        allowUpdates: false
        artifacts: HLTextureToolsCLI
